server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /widget/index.html;
        # Bitrix24 шлёт POST при открытии виджета — принимаем как GET
        error_page 405 =200 /widget/index.html;
    }
}
